version: '3.7'

networks:
  walmart-net:

services:
  walmart-api:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "3030:3030"
    container_name: walmart-api
    links:
      - mongo-db
    env_file: .env
    environment:
      - PORT=3030
      - DB_URI=mongodb://127.0.0.1:27017 
      - DB_USER=productListUser 
      - DB_PASS=productListPassword 
      - DB_NAME=promotions 
      - NODE_ENV=development
    restart: always
    depends_on:
      - mongo-db
    networks:
      walmart-net:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongodb-local
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: productListUser
      MONGO_INITDB_ROOT_PASSWORD: productListPassword
      MONGO_INITDB_DATABASE: promotions
    volumes:
      - db/:/data/db
    networks:
      walmart-net: